version: "3.8"
services:
  cryptotraderai:
    build: .
    ports:
      - "8000:8000" # Map the container's port 8000 to the host's port 8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
